# Generated by Django 5.1.5 on 2025-01-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold_weight',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
