# Generated by Django 5.1.5 on 2025-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gold_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='a', max_length=64, unique=True, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
