version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-django-khanetala
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword  # Add a password here
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: khanetala
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ''
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - app

volumes:
  postgres_data: