# Generated by Django 5.1.5 on 2025-01-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('S', 'موفق'), ('P', 'در حال انجام'), ('F', 'ناموفق')], default='P', max_length=1, verbose_name='وضعیت')),
                ('transaction_type', models.CharField(choices=[('B', 'خرید'), ('S', 'فروش'), ('C', 'شارژ')], max_length=1, verbose_name='نوع تراکنش')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ')),
                ('gold_amount_gr', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
