# Generated by Django 5.1.5 on 2025-01-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_rial',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='gold_amount_gr',
            new_name='gold_weight_gram',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=4, default=10000000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('B', 'خرید'), ('S', 'فروش')], max_length=1, verbose_name='نوع تراکنش'),
        ),
    ]
